# Source: https://raw.githubusercontent.com/jazzbre/gekko/stable/strategies/MACD.js
short = [1,20]
long = [20,50]
signal = [1,12]
interval = [1,50]

[thresholds]
down = [-0.5,0]
up = [0,0.5]
persistence = [0,10]
